### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ethedev**

### CODE REVIEW

**Comment by byterose** [comment]
@ethedev it looks like this will be added in #88, let's close this pr then to avoid any confusion.﻿

**Comment by byterose** [comment]
@ElmosArmy thoughts?﻿

**Comment by ElmoArmy** [comment]
> @ElmoArmy thoughts?

Yea, no problem closing this one and having it all be included in #88, that's what you mean right?

**Comment by byterose** [comment]
> > @ethedev it looks like this will be added in #88, let's close this pr then to avoid any confusion.
> 
> #88 targets develop and this pr targets master merging develop with master. I'm not sure what the confusion you are referring to. Could you clarify?

According to the title I thought this pr was only for adding the new assets.json test file.
I'll just rename this pr then if it should merge everything into master at the end.

**Comment by ElmoArmy** [comment]
> > > @ethedev it looks like this will be added in #88, let's close this pr then to avoid any confusion.
> > 
> > 
> > #88 targets develop and this pr targets master merging develop with master. I'm not sure what the confusion you are referring to. Could you clarify?
> 
> According to the title I thought this pr was only for adding the new assets.json test file. I'll just rename this pr then if it should merge everything into master at the end.

Ok yes, I agree with this. The title was a bit confusing.

**Comment by ethedev** [comment]
@ElmoArmy was the other commits previously tested on its own branch? and is there anything more you want to add or is that ready for checks?
@byterose this was only for the test assets file to be directly on develop

**Comment by byterose** [comment]
@ethedev Every commit on develop was reviewed and tested before.

**Pull request closed without merging**
